### ISSUE TITLE
No Group Policies in Drop-Down

### ISSUE THREAD

**Issue by JLester73** [jperryNPS/GroupPolicyNetworkLocations#6]
When I launch the program, there's nothing in the drop-down.  I tried launching as Administrator and running it from a DC directly, but still nothing listed.

**Comment by shodiwarmic** [comment]
This is because of issue #2.

The program is unable to create the XML files in a way that is recognized by the GPO, so you must manually create at least one of each of the following settings in the GPO for it to show up in the drop-down. They can be dummy info, the program will completely rewrite the XML files when you save the object.

- IniFile settings (User Configuration>Preferences>Windows Settings>IniFiles)
- Folder setting (User Configuration>Preferences>Windows Settings>Folders)
- Shortcut setting (User Configuration>Preferences>Windows Settings>Shortcuts)
